### ISSUE TITLE
Pre-trained models and `classify` disappeared?

### ISSUE THREAD

**Issue by roland-KA** [FluxML/Metalhead.jl#143]
About a year ago I used `Metalhead.jl` for some demonstration purposes as described here: https://juliapackages.com/p/metalhead using the `classify`-function.

Now the pre-trained models as well as the `classify`-function seem to have disappeared. What happened to this and how can I do it now?

**Comment by darsnack** [comment]
You will need to pin Metalhead to v0.5.x, since we made an intentional decision to remove datasets and the terminal viewer code from Metalhead.

As for the pre-trained models, we were initially going to keep the weights for the ones that are in the repo, but our testing indicated that the model predictions were not always correct. We opted to remove the weights as part of the complete breaking refactor in v0.6. You can still access the old pre-trained models with v0.5.x. In the coming weeks, we plan to add back pre-trained weights for VGG and ResNet variants (you can follow https://github.com/FluxML/MetalheadWeights/pull/2 to track this).

If you want to use Metalhead v0.6+, then you can recreate the old functionality. The old Metalhead assumed that you had an installation of ImageNet. Assuming you have that and that `imagenet_labels` corresponds to a vector of all the possible ImageNet labels, you can define:
```julia
classify(model, input) = Flux.onecold(model(input), imagenet_labels)
```
If you can provide more details about your ImageNet installation, I can help you recreate the data loading as well (i.e. providing the `imagenet_labels` above).

**Comment by ToucheSir** [comment]
> our testing indicated that the model predictions were not always correct.

Not even that, the first few examples we pulled were flat out wrong. There's an issue about it kicking around on this repo if you're interested.

**Comment by roland-KA** [comment]
Thanks all together for this really fast feedback! I will first try it with v0.5 and then have a look on the other alternative mentioned based on the current version.
