### ISSUE TITLE
Make CUDA an optional dependency in Julia 1.9

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Metalhead.jl#250]
### Motivation and description

CUDA and GPUCompiler are heavy dependencies and are often not needed in non-CUDA systems.

### Possible Implementation

The new pkg extensions in Julia1.9 can be used.

**Comment by ToucheSir** [comment]
The only code which relies on CUDA.jl is https://github.com/FluxML/Metalhead.jl/blob/4e5b8f16964468518eeb6eb8d7e5f85af4ecf959/src/layers/drop.jl#L48C1-L52, so extracting that into an extension should be sufficient.

**Comment by ToucheSir** [comment]
For RNGs? Probably not, because I don't think the GPU packages have a common interface or supertype for their RNG types. 

Some sort of getter for the train/test status of a layer would be a nice addition to Flux. I think we'd just have to bikeshed the name. _isactive as used internally does something other than that.
